"""Borrado en cascada en historial_cambios.mantenimiento_id

Revision ID: 13effdb2de6b
Revises: 5fecdd235b54
Create Date: 2025-07-12 14:33:21.690843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13effdb2de6b'
down_revision = '5fecdd235b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')  # Comentado porque causa error en SQLite
        batch_op.create_foreign_key('fk_historial_cambios_mantenimiento_id', 'programado', ['mantenimiento_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')  # Comentado porque causa error en SQLite
        batch_op.create_foreign_key('fk_historial_cambios_mantenimiento_id', 'programado', ['mantenimiento_id'], ['id'])

    # ### end Alembic commands ###
