"""agregar_campo_company_id_a_programado

Revision ID: 18dc6a181997
Revises: bb5a3c13c68d
Create Date: 2025-06-05 08:52:43.512057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dc6a181997'
down_revision = 'bb5a3c13c68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_equipos_company', 'empresa', ['company_id'], ['id'])

    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('servicio',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('repuestos',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('herramientas',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('autorizado_por',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('motivo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('frecuencia',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('observaciones',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_programado_company', 'empresa', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_programado_equipo', 'equipos', ['codigo'], ['codigo'])
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_programado_equipo', type_='foreignkey')
        batch_op.drop_constraint('fk_programado_company', type_='foreignkey')
        batch_op.alter_column('observaciones',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('frecuencia',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('motivo',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('autorizado_por',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('herramientas',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('repuestos',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('servicio',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipos_company', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
