"""Agregar campo manuales a Equipo

Revision ID: 24f48a10732c
Revises: 5c2785a3cac3
Create Date: 2025-06-17 15:08:46.575534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f48a10732c'
down_revision = '5c2785a3cac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('manuales', sa.Boolean(), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('manuales')

    # ### end Alembic commands ###
