"""Agregar tabla Lubricacion

Revision ID: 250c3bd026e2
Revises: bb08aca15cc4
Create Date: 2025-06-21 12:52:31.560024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250c3bd026e2'
down_revision = 'bb08aca15cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('lubricacion',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('equipo_codigo', sa.String(length=50), nullable=False),
    # sa.Column('numero', sa.Integer(), nullable=True),
    # sa.Column('mecanismo', sa.String(length=200), nullable=True),
    # sa.Column('cantidad', sa.String(length=50), nullable=True),
    # sa.Column('tipo_lubricante', sa.String(length=100), nullable=True),
    # sa.Column('producto', sa.String(length=100), nullable=True),
    # sa.Column('metodo_lubricacion', sa.String(length=100), nullable=True),
    # sa.Column('frecuencia_inspeccion', sa.String(length=100), nullable=True),
    # sa.Column('observaciones', sa.Text(), nullable=True),
    # sa.ForeignKeyConstraint(['equipo_codigo'], ['equipos.codigo'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lubricacion')
    # ### end Alembic commands ###
