"""Agregar tabla equipos_medicion y relación con Equipo

Revision ID: 3a5d23ea3122
Revises: 3fcdfa189c82
Create Date: 2025-06-18 11:22:15.040116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5d23ea3122'
down_revision = '3fcdfa189c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('equipos_medicion',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('equipo_codigo', sa.String(length=50), nullable=False),
    # sa.Column('codigo', sa.String(length=50), nullable=False),
    # sa.Column('nombre', sa.String(length=100), nullable=False),
    # sa.Column('ubicacion', sa.String(length=100), nullable=True),
    # sa.ForeignKeyConstraint(['equipo_codigo'], ['equipos.codigo'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipos_medicion')
    # ### end Alembic commands ###
