"""Agregar campo fecha_fabricacion a Equipo

Revision ID: 3fcdfa189c82
Revises: 69d1209623c9
Create Date: 2025-06-17 16:07:56.431039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcdfa189c82'
down_revision = '69d1209623c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('fecha_fabricacion', sa.String(length=50), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('fecha_fabricacion')

    # ### end Alembic commands ###
