"""Cambiar campos registro_nuevo y actualizacion a booleanos

Revision ID: 4a9791131aaa
Revises: dcfd133a0640
Create Date: 2025-06-11 12:08:16.567422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9791131aaa'
down_revision = 'dcfd133a0640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.alter_column('registro_nuevo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('actualizacion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), server_default=sa.text("'Sin nombre'"), nullable=False))

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.alter_column('actualizacion',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('registro_nuevo',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
