"""Agregar campo proceso a Equipo

Revision ID: 5c2785a3cac3
Revises: ea5ea1a75d80
Create Date: 2025-06-17 13:32:17.466939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2785a3cac3'
down_revision = 'ea5ea1a75d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('proceso', sa.String(length=100), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('proceso')

    # ### end Alembic commands ###
