"""agregar_campo_recibido_por_a_programado

Revision ID: 5fecdd235b54
Revises: 5aa7d3f73590
Create Date: 2025-07-12 10:19:59.402762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fecdd235b54'
down_revision = '5aa7d3f73590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recibido_por', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.drop_column('recibido_por')

    # ### end Alembic commands ###
