"""Agregar campo tipo_instalacion a Equipo

Revision ID: 69d1209623c9
Revises: 24f48a10732c
Create Date: 2025-06-17 15:37:47.983373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d1209623c9'
down_revision = '24f48a10732c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('tipo_instalacion', sa.String(length=50), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('tipo_instalacion')

    # ### end Alembic commands ###
