"""eliminar campo imagen de lubricacion

Revision ID: 7dc75ec28322
Revises: 80de1e703ea4
Create Date: 2025-06-24 13:15:02.121467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc75ec28322'
down_revision = '80de1e703ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('lubricacion', schema=None) as batch_op:
    #     batch_op.drop_column('imagen')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lubricacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
