"""agregar campo imagen_lubricacion a equipo

Revision ID: 80de1e703ea4
Revises: 2e587e96932a
Create Date: 2025-06-24 11:25:52.290748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80de1e703ea4'
down_revision = '2e587e96932a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('equipos', schema=None) as batch_op:
    #     batch_op.alter_column('frecuencia_mantenimiento',
    #            existing_type=sa.VARCHAR(length=100),
    #            type_=sa.String(length=30),
    #            existing_nullable=True)

    # with op.batch_alter_table('lubricacion', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lubricacion', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.alter_column('frecuencia_mantenimiento',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
