"""Agregar tabla historial_equipos

Revision ID: 8f58ff155a90
Revises: 3a5d23ea3122
Create Date: 2025-06-18 11:33:59.203468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f58ff155a90'
down_revision = '3a5d23ea3122'
branch_labels = None
depends_on = None


def upgrade():
    # op.create_table('historial_equipos',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('equipo_codigo', sa.String(length=50), nullable=False),
    #     sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    #     sa.Column('tipo_cambio', sa.String(length=50), nullable=False),
    #     sa.Column('campo_modificado', sa.String(length=100), nullable=True),
    #     sa.Column('valor_anterior', sa.String(length=500), nullable=True),
    #     sa.Column('valor_nuevo', sa.String(length=500), nullable=True),
    #     sa.Column('usuario', sa.String(length=100), nullable=True),
    #     sa.Column('observaciones', sa.String(length=500), nullable=True),
    #     sa.PrimaryKeyConstraint('id'),
    #     sa.ForeignKeyConstraint(['equipo_codigo'], ['equipos.codigo'], ),
    # )
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_equipos')
    # ### end Alembic commands ###
