"""Agregar campo centro_costos a equipos

Revision ID: bb08aca15cc4
Revises: 8f58ff155a90
Create Date: 2025-06-20 10:11:19.695966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb08aca15cc4'
down_revision = '8f58ff155a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('programado_temp')
    # with op.batch_alter_table('equipos', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('centro_costos', sa.String(length=100), nullable=True))
    pass

    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.alter_column('autorizado_por',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.alter_column('autorizado_por',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('centro_costos')

    op.create_table('programado_temp',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_prog', sa.DATE(), nullable=False),
    sa.Column('hora', sa.VARCHAR(length=5), nullable=True),
    sa.Column('servicio', sa.VARCHAR(length=200), nullable=False),
    sa.Column('tipo_mantenimiento', sa.VARCHAR(length=50), nullable=False),
    sa.Column('tiempo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('repuestos', sa.VARCHAR(length=200), nullable=True),
    sa.Column('herramientas', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('autorizado_por', sa.VARCHAR(length=100), nullable=True),
    sa.Column('estado_inicial', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado_final', sa.VARCHAR(length=50), nullable=True),
    sa.Column('motivo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('costo_rep', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('costo_herram', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('costo_mdo', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('costo_total', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('frecuencia', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prox_mtto', sa.DATE(), nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tecnico_asignado', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tecnico_realizador', sa.VARCHAR(length=100), nullable=True),
    sa.Column('hora_inicial', sa.DATETIME(), nullable=True),
    sa.Column('hora_final', sa.DATETIME(), nullable=True),
    sa.Column('tiempo_gastado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
