"""Dividir checklist equipo_o_maquina en es_equipo y es_maquina

Revision ID: c06f60e1f70e
Revises: df0ecd29e183
Create Date: 2025-06-17 09:06:06.141103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06f60e1f70e'
down_revision = 'df0ecd29e183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('es_equipo', sa.Boolean(), nullable=True))
        # batch_op.add_column(sa.Column('es_maquina', sa.Boolean(), nullable=True))
        # batch_op.drop_column('equipo_maquina')
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('equipo_maquina', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('es_maquina')
        batch_op.drop_column('es_equipo')
        pass

    # ### end Alembic commands ###
