"""Agregar campos de checklists al modelo Equipo

Revision ID: df0ecd29e183
Revises: f1a879c6ebe1
Create Date: 2025-06-17 08:44:29.658396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0ecd29e183'
down_revision = 'f1a879c6ebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.alter_column('acciones',
        #        existing_type=sa.String(length=100),
        #        type_=sa.VARCHAR(length=50),
        #        existing_nullable=True)
        # batch_op.alter_column('tipo_energia',
        #        existing_type=sa.String(length=255),
        #        type_=sa.VARCHAR(length=100),
        #        existing_nullable=True)
        # batch_op.drop_column('registro_mantenimientos')
        # batch_op.drop_column('certificaciones')
        # batch_op.drop_column('manual_usuario')
        # batch_op.drop_column('procedimientos_operacion')
        # batch_op.drop_column('inspeccion_seguridad')
        # batch_op.drop_column('plan_mantenimiento')
        # batch_op.drop_column('preoperacional')
        # batch_op.drop_column('equipo_maquina')
        # batch_op.drop_column('hoja_vida')
        # batch_op.drop_column('ficha_tecnica')
        pass

    # ### end Alembic commands ###
