"""Actualizar modelo de motores y relaciones

Revision ID: e6e7d4be367b
Revises: 4a9791131aaa
Create Date: 2025-06-11 16:46:21.822367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e7d4be367b'
down_revision = '4a9791131aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motores_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('potencia', sa.String(length=50), nullable=True),
    sa.Column('voltaje', sa.String(length=50), nullable=True),
    sa.Column('corriente', sa.String(length=50), nullable=True),
    sa.Column('rpm', sa.String(length=50), nullable=True),
    sa.Column('eficiencia', sa.String(length=50), nullable=True),
    sa.Column('rotacion', sa.String(length=50), nullable=True),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('ultima_revision', sa.Date(), nullable=True),
    sa.Column('proxima_revision', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['equipo_codigo'], ['equipos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('motores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('equipo_codigo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nomb_Motor', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descrip_Motor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_Motor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dirRotacion_Motor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rpm_Motor', sa.VARCHAR(length=50), nullable=True),
    sa.Column('eficiencia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('corriente_Motor', sa.VARCHAR(length=50), nullable=True),
    sa.Column('potencia_Motor', sa.VARCHAR(length=50), nullable=True),
    sa.Column('voltaje_Motor', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipo_codigo'], ['equipos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('motores_equipo')
    # ### end Alembic commands ###
