"""Agregar método de codificación y frecuencia de mantenimiento a Equipo

Revision ID: ea5ea1a75d80
Revises: ca975e0e1443
Create Date: 2025-06-17 13:04:51.557009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5ea1a75d80'
down_revision = 'ca975e0e1443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('metodo_codificacion', sa.String(length=100), nullable=True))
        # batch_op.add_column(sa.Column('frecuencia_mantenimiento', sa.String(length=30), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('frecuencia_mantenimiento')
        batch_op.drop_column('metodo_codificacion')

    # ### end Alembic commands ###
