"""Agrega/renombra campo nomb_Motor en motores_equipo

Revision ID: f1a879c6ebe1
Revises: e6e7d4be367b
Create Date: 2025-06-13 11:48:50.719123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a879c6ebe1'
down_revision = 'e6e7d4be367b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motores_equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomb_Motor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('descrip_Motor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipo_Motor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('potencia_Motor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('voltaje_Motor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('corriente_Motor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rpm_Motor', sa.String(length=50), nullable=True))
        batch_op.drop_column('estado')
        batch_op.drop_column('potencia')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('voltaje')
        batch_op.drop_column('rpm')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('corriente')
        batch_op.drop_column('fecha_instalacion')
        batch_op.drop_column('proxima_revision')
        batch_op.drop_column('tipo')
        batch_op.drop_column('ultima_revision')

    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programado', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('motores_equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_revision', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('proxima_revision', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('fecha_instalacion', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('corriente', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('rpm', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('voltaje', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('potencia', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('rpm_Motor')
        batch_op.drop_column('corriente_Motor')
        batch_op.drop_column('voltaje_Motor')
        batch_op.drop_column('potencia_Motor')
        batch_op.drop_column('tipo_Motor')
        batch_op.drop_column('descrip_Motor')
        batch_op.drop_column('nomb_Motor')

    # ### end Alembic commands ###
