"""Agregar tabla auditoria

Revision ID: ff75e5cfcea3
Revises: 7dc75ec28322
Create Date: 2025-07-07 17:29:52.746884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff75e5cfcea3'
down_revision = '7dc75ec28322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lubricacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_codigo', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('mecanismo', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.String(length=50), nullable=True),
    sa.Column('tipo_lubricante', sa.String(length=100), nullable=True),
    sa.Column('producto', sa.String(length=100), nullable=True),
    sa.Column('metodo_lubricacion', sa.String(length=100), nullable=True),
    sa.Column('frecuencia_inspeccion', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_codigo'], ['equipos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_equipos')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cartas_lubricacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('imagen_lubricacion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('imagen_lubricacion')
        batch_op.drop_column('cartas_lubricacion')

    op.create_table('_alembic_tmp_equipos',
    sa.Column('codigo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_ingreso', sa.DATE(), nullable=True),
    sa.Column('registro_nuevo', sa.BOOLEAN(), nullable=True),
    sa.Column('actualizacion', sa.BOOLEAN(), nullable=True),
    sa.Column('num_fabricacion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fabricante', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nom_contacto', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=100), nullable=True),
    sa.Column('propietario', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_eq', sa.VARCHAR(length=100), nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_control', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('clase', sa.VARCHAR(length=100), nullable=True),
    sa.Column('marca', sa.VARCHAR(length=100), nullable=True),
    sa.Column('referencia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('serie', sa.VARCHAR(length=100), nullable=True),
    sa.Column('color', sa.VARCHAR(length=100), nullable=True),
    sa.Column('altura', sa.VARCHAR(length=100), nullable=True),
    sa.Column('largo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ancho', sa.VARCHAR(length=100), nullable=True),
    sa.Column('peso', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_energia', sa.VARCHAR(length=255), nullable=True),
    sa.Column('corriente', sa.VARCHAR(length=50), nullable=True),
    sa.Column('potencia', sa.VARCHAR(length=50), nullable=True),
    sa.Column('voltaje', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_refrig', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_comb', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_lub', sa.VARCHAR(length=50), nullable=True),
    sa.Column('repuestos', sa.VARCHAR(length=50), nullable=True),
    sa.Column('estado_eq', sa.VARCHAR(length=50), nullable=True),
    sa.Column('n_motores', sa.INTEGER(), nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=100), nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=150), nullable=True),
    sa.Column('hist_mtto', sa.VARCHAR(length=150), nullable=True),
    sa.Column('funcion_maq', sa.VARCHAR(length=150), nullable=True),
    sa.Column('operacion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('mecanico', sa.VARCHAR(length=50), nullable=True),
    sa.Column('electrico', sa.VARCHAR(length=50), nullable=True),
    sa.Column('partes', sa.VARCHAR(length=50), nullable=True),
    sa.Column('acciones', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('ficha_tecnica', sa.BOOLEAN(), nullable=True),
    sa.Column('hoja_vida', sa.BOOLEAN(), nullable=True),
    sa.Column('es_equipo', sa.BOOLEAN(), nullable=True),
    sa.Column('es_maquina', sa.BOOLEAN(), nullable=True),
    sa.Column('preoperacional', sa.BOOLEAN(), nullable=True),
    sa.Column('plan_mantenimiento', sa.BOOLEAN(), nullable=True),
    sa.Column('inspeccion_seguridad', sa.BOOLEAN(), nullable=True),
    sa.Column('procedimientos_operacion', sa.BOOLEAN(), nullable=True),
    sa.Column('manual_usuario', sa.BOOLEAN(), nullable=True),
    sa.Column('certificaciones', sa.BOOLEAN(), nullable=True),
    sa.Column('registro_mantenimientos', sa.BOOLEAN(), nullable=True),
    sa.Column('anios_operacion', sa.VARCHAR(length=20), nullable=True),
    sa.Column('instructivos_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('estandar_seguridad_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('instructivos_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('estandar_seguridad_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('operacion_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('mecanico_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('electrico_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('partes_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('metodo_codificacion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('frecuencia_mantenimiento', sa.VARCHAR(length=30), nullable=True),
    sa.Column('proceso', sa.VARCHAR(length=100), nullable=True),
    sa.Column('centro_costos', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manuales', sa.BOOLEAN(), nullable=True),
    sa.Column('tipo_instalacion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_fabricacion', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.drop_table('lubricacion')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
